"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SETTINGS_PATH = os.path.dirname(os.path.dirname(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '6t8i%h4dee3gnipi0(jaq713k+=9@awqme@e*j%au)g)z+-c9i'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Configure your allowed hosts
ALLOWED_HOSTS = []

# CORS
CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]
# ===
# Internationalization
# ===
# Language
LANGUAGE_CODE = 'en-us'  # or other appropriate code
USE_I18N = True
USE_L10N = True
LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]
LANGUAGES =[ 
    ('en', _('English')),
    ('de', _('German')),
    ('es', _('Spanish')),
]

# Time zone
TIME_ZONE = 'UTC'
USE_TZ = True

# Application definition
INSTALLED_APPS = [
    'users.apps.UsersConfig',
    # 'django_generate_secret_key', # Secret key generation
    'django_extensions',
    'rest_framework',
    # 'corsheaders', # Cors headers handling
    'storages',
    # 'admin_interface', # Admin console customization
    # 'colorfield', # Admin interface color picker for admin_interface app
    # 'django.contrib.admindocs', # Django admin documentation
    # 'drf_yasg', # Django rest configuration
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.locale.LocaleMiddleware', # Support for localization
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Configured to fin templates
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# Configured to find tempalte directions from every app
TEMPLATE_DIRS = (
    os.path.join(SETTINGS_PATH, 'templates'),
)

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

# Configured for debbugging and production
if 'RDS_DB_NAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

# Custom user model
AUTH_USER_MODEL = 'users.GeneralUser'

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# https://docs.djangoproject.com/en/3.0/topics/i18n/


# https://docs.djangoproject.com/en/3.0/howto/static-files/
# Static files configured for remote and local support
if 'RDS_DB_NAME' in os.environ:

    # AWS S3 bucket configuraton
    AWS_ACCESS_KEY_ID = os.environ['S3_ACCESS_KEY_ID'] # 'AKIAIT2Z5TDYPX3ARJBA'
    AWS_SECRET_ACCESS_KEY = os.environ['S3_SECRET_ACCESS_KEY'] # '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'
    AWS_STORAGE_BUCKET_NAME = os.environ['S3_STORAGE_BUCKET_NAME'] # 'sibtc-static'
    AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME
    AWS_S3_OBJECT_PARAMETERS = {
        'CacheControl': 'max-age=86400',
    }
    AWS_LOCATION = 'static'

    STATIC_URL = 'https://%s/%s/' % (AWS_S3_CUSTOM_DOMAIN, AWS_LOCATION)
    DEFAULT_FILE_STORAGE = 'backend.s3utils.MediaRootS3BotoStorage'
    STATICFILES_STORAGE = 'backend.s3utils.StaticRootS3BotoStorage'
else:
    STATIC_URL = '/static/'
    MEDIA_URL = '/media/'
    STATIC_ROOT = ''
    MEDIA_ROOT = ''
    STATICFILES_DIRS =(
        os.path.join(SETTINGS_PATH, 'static'),
    )